/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2015-10-08 08:57:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import cn.bluemobi.constant.BlueMobiConstant;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/page/admin/../basePath.jsp", Long.valueOf(1437105433780L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
 
//String basePath=BlueMobiConstant.domain; 
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\" />");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" contenttype=\"text/xml; charset=UTF-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>登陆页面</title>\r\n");
      out.write("<link type=\"text/css\" href=\"resource/css/loginModel.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"resource/jquery-1.7.2.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"resource/css/basic.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"resource/js/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resource/js/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resource/js/publicSystem.js\"></script>\r\n");
      out.write("<link id=\"easyuiTheme\" rel=\"stylesheet\" href=\"resource/js/jquery-easyui-1.3.5/themes/default/easyui.css\" type=\"text/css\">\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"resource/css/icon.css\"></link>\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(top.location!=self.location){\r\n");
      out.write("\t\t\ttop.location=$(\"base\")[0].href+\"admin/login.htm?uuid=\"+Math.random();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#code\").attr(\"src\",$(\"base\")[0].href+\"auth/code.htm?uuid=\"+Math.random());\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#code\").bind(\"click\",function(){\r\n");
      out.write("\t\t\t$(this).attr(\"src\",$(\"base\")[0].href+\"auth/code.htm?uuid=\"+Math.random());\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"==\"exception\"){\r\n");
      out.write("\t\t\t$.messager.show({title:'',msg:'请输入账号、密码和验证码',showType:'fade',timeout:1500,style:{right:'',top:180,bottom:''}});\r\n");
      out.write("\t\t}else if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"==\"error\"){\r\n");
      out.write("\t\t\t$.messager.show({title:'',msg:'账号或者密码不正确',showType:'fade',timeout:1500,style:{right:'',top:180,bottom:''}});\r\n");
      out.write("\t\t}else if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"==\"codeError\"){\r\n");
      out.write("\t\t\t$(\"#account\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${adminUser.account}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\");\t\t\t\r\n");
      out.write("\t\t\t$(\"#password\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${adminUser.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\");\t\t\t\r\n");
      out.write("\t\t\t$.messager.show({title:'',msg:'验证码错误',showType:'fade',timeout:1500,style:{right:'',top:180,bottom:''}});\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#account\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\");\t\t\r\n");
      out.write("\t\t\tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${flag}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"!=\"\"){\r\n");
      out.write("\t\t\t\t$(\"#checkbox\").attr(\"checked\",\"checked\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction submitValidate(){\r\n");
      out.write("\t\tvar account=$(\"#account\").val();\r\n");
      out.write("\t\tvar password=$(\"#password\").val();\r\n");
      out.write("\t\tvar code=$(\"#codeStr\").val();\r\n");
      out.write("\t\tif(account==''){\r\n");
      out.write("\t\t\t$.messager.show({title:'',msg:'请输入账号',showType:'fade',timeout:1500,style:{right:'',top:180,bottom:''}});\r\n");
      out.write("\t\t}else if(password==''){\r\n");
      out.write("\t\t\t$.messager.show({title:'',msg:'请输入用户密码',showType:'fade',timeout:1500,style:{right:'',top:180,bottom:''}});\r\n");
      out.write("\t\t}else if(code==''){\r\n");
      out.write("\t\t\t$.messager.show({title:'',msg:'请输入验证码',showType:'fade',timeout:1500,style:{right:'',top:180,bottom:''}});\r\n");
      out.write("\t\t}else{\t\r\n");
      out.write("\t\t\t$(\"#loginForm\").submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//支持回车提交\r\n");
      out.write("\t$(document).keyup(function(event){\r\n");
      out.write("\t  if(event.keyCode ==13){\r\n");
      out.write("\t    $(\".login\").trigger(\"click\");\r\n");
      out.write("\t  }\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\t\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("<div id=\"container\" style=\"margin-left: 15%;\">\r\n");
      out.write("\t\t<div class=\"logo\" style=\"margin-left:35%;\">\r\n");
      out.write("\t\t\t<a href=\"#\"><img src=\"imgs/yingwangkeji.png\" alt=\"\" style=\"position: relative; bottom: 50px\"/></a>\r\n");
      out.write("\t\t</div >\r\n");
      out.write("\t\t<div id=\"box\" style=\"margin-left: 15%;width:70%;overflow: auto\">\r\n");
      out.write("\t\t\t<form id=\"loginForm\" action=\"admin/login/submit.htm\" method=\"post\">\r\n");
      out.write("\t\t\t<p class=\"main\">\r\n");
      out.write("\t\t\t\t<label>账&nbsp;&nbsp;&nbsp;号: </label>\r\n");
      out.write("\t\t\t\t<input id=\"account\" name=\"account\" maxlength=\"30\" placeholder=\"请输入账号\" /> \r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p class=\"main\">\r\n");
      out.write("\t\t\t\t<label>密&nbsp;&nbsp;&nbsp;码: </label>\r\n");
      out.write("\t\t\t\t<input id=\"password\" type=\"password\" maxlength=\"30\" name=\"password\" placeholder=\"请输入密码\">\t\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p class=\"main\">\r\n");
      out.write("\t\t\t\t<label>验证码: </label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"codeStr\" name=\"code\" maxlength=\"4\" placeholder=\"请输入验证码\" style=\"width:100px\">&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<img id=\"code\" alt=\"看不清？点一下\" height=\"28px\"\">\t\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<!-- \r\n");
      out.write("\t\t\t<p class=\"space\">\r\n");
      out.write("\t\t\t\t<span><input id=\"checkbox\" type=\"checkbox\" name=\"remaberMe\" value=\"1\"/>记住我</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t -->\r\n");
      out.write("\t\t\t<p class=\"space\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" onclick=\"submitValidate()\" value=\"登录\" class=\"login\" style=\"margin-right: 200px\"/>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
